name: Database Backup to Azure (ihundred,intranet)

on:
  schedule:
    - cron: '0 2 * * *'  # Every day at 2 AM UTC
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # ✅ Use stable Python version

      - name: Install AzCopy
        run: |
          curl -sL https://aka.ms/downloadazcopy-v10-linux | tar -xz
          sudo cp ./azcopy_linux_amd64*/azcopy /usr/bin/

      - name: Run Backup Script
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: "5432"
          DB_NAME: ${{ secrets.DB_NAME }}
          INTRANET_DB_NAME: ${{ secrets.INTRANET_DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          BACKUP_DIR: "/tmp/backups"
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_CONTAINER: ${{ secrets.AZURE_STORAGE_CONTAINER }}
          INTRANET_AZURE_STORAGE_CONTAINER: ${{ secrets.INTRANET_AZURE_STORAGE_CONTAINER }}
          AZURE_SAS_TOKEN: ${{ secrets.AZURE_SAS_TOKEN }}
        run: |
          pip install --upgrade pip
          python ihundred_dump.py
          python intranet_dump.py
